[tool.ruff]
# Same as Black.
line-length = 127
# Assume Python 3.9
target-version = "py39"

[tool.ruff.lint]
select = ["E", "F", "B", "UP", "C90", "RUF"]
# B028: Ignore explicit stacklevel`
# RUF013: Too many false positives (implicit optional)
ignore = ["B028", "RUF013"]

[tool.ruff.lint.per-file-ignores]
# ClassVar, implicit optional check not needed for tests
"./tests/*.py" = ["RUF012", "RUF013"]

[tool.ruff.lint.mccabe]
# Unlike Flake8, ruff default to a complexity level of 10.
max-complexity = 15

[tool.black]
line-length = 127

[tool.mypy]
ignore_missing_imports = true
follow_imports = "silent"
show_error_codes = true
exclude = """(?x)(
	sb3_contrib/ppo_recurrent/ppo_recurrent.py$
	| sb3_contrib/ars/ars.py$
	| sb3_contrib/common/recurrent/policies.py$
	| sb3_contrib/common/recurrent/buffers.py$
	| tests/test_train_eval_mode.py$
  )"""

[tool.pytest.ini_options]
# Deterministic ordering for tests; useful for pytest-xdist.
env = ["PYTHONHASHSEED=0"]

filterwarnings = [
    # Tensorboard warnings
    "ignore::DeprecationWarning:tensorboard",
    # tqdm warning about rich being experimental
    "ignore:rich is experimental",
]
markers = ["slow: marks tests as slow (deselect with '-m \"not slow\"')"]

[tool.coverage.run]
disable_warnings = ["couldnt-parse"]
branch = false
omit = ["tests/*", "setup.py"]

[tool.coverage.report]
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError()",
    "if typing.TYPE_CHECKING:",
]

# [tool.pyright]
# extraPaths = ["../torchy-baselines/"]

[project]
name = "stable-baselines3-contrib-grpo"
version = "0.1.0"
description = ""
authors = [
    {name = "Florian Bauer",email = "florian.bauer@adago.de"}
]
readme = "README.md"
requires-python = ">=3.10"

[tool.poetry]
package-mode = false

[tool.poetry.dependencies]
python = ">=3.10"
stable-baselines3 = { git = "https://github.com/DLR-RM/stable-baselines3", branch = "master" }  # use newest SB3 version
ale-py = ">=0.9.0"
cloudpickle = "*"
gymnasium = ">=0.29.1,<1.2.0"
matplotlib = "*"
numpy = ">=1.20,<3.0"
opencv-python = "*"
pandas = "*"
pillow = "*"
psutil = "*"
pygame = "*"
rich = "*"
tensorboard = ">=2.9.1"
torch = ">=2.3,<3.0"
tqdm = "*"
ruff = "^0.11.12"
black = "^25.1.0"
isort = "^6.0.1"
snakeviz = "^2.2.2"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
