CartPole-v1:
  n_timesteps: !!float 1e5
  policy: 'GroupPolicy'
  group_rollout_buffer_class: 'ProcessGroupBuffer'
  group_size: 4
  # n_epochs: 20
  n_epochs: 5
  # ent_coef: 0.0
  ent_coef: 0.002
  # learning_rate: lin_0.001
  learning_rate: !!float 9e-05
  # clip_range: lin_0.2
  clip_range: !!float 0.3
  max_grad_norm: 0.784
  policy_kwargs: "dict(activation_fn=nn.ELU, net_arch=dict(pi=[64, 64]))"

MountainCar-v0:
  normalize: true
  n_timesteps: !!float 1e6
  policy: 'GroupPolicy'
  group_rollout_buffer_class: 'ProcessGroupBuffer'
  group_size: 16
  n_epochs: 10